# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('news', '0002_newspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='intro',
        ),
        migrations.AddField(
            model_name='newspage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Текст'),
        ),
    ]
