# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180218_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
