# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 03:13
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newspage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='sidebar',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
