# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogIndexPage',
            new_name='AllServicePage',
        ),
    ]
