# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 23:29
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_testimonialimage'),
        ('service', '0002_auto_20180217_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='allservicepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='category_in_price', to='home.CategoryPrice'),
        ),
    ]
