# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homesliderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesliderimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image', verbose_name='Изображения для слайдера'),
        ),
    ]
