# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 09:12
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180213_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='text_col1',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Текст в первой колонке', verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='text_col2',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Текст во второй колонке', verbose_name='Текст 2'),
        ),
    ]
