# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_aboutsliderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsliderimage',
            name='block_animation',
            field=models.CharField(blank=True, choices=[('mn', 'Главная'), ('en', 'Абитуриентам'), ('st', 'Студентам'), ('ct', 'Контакты')], max_length=250),
        ),
    ]
