# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 10:04
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180213_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='point1',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Наши преимущества - текст в первой ячейке', verbose_name='Преимущества1'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='point2',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Наши преимущества - текст во второй ячейке', verbose_name='Преимущества2'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='point3',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Наши преимущества - текст в третьей ячейке', verbose_name='Преимущества3'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='point4',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Наши преимущества - текст в четвёртой ячейке', verbose_name='Преимущества4'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='point5',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Наши преимущества - текст в пятой ячейке', verbose_name='Преимущества5'),
        ),
    ]
