# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_worklistimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklistimage',
            name='h3_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='worklistimage',
            name='text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='worklistimage',
            name='image1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image', verbose_name='Изобр. 1'),
        ),
        migrations.AlterField(
            model_name='worklistimage',
            name='image2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image', verbose_name='Изобр. 2'),
        ),
    ]
