# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 08:26
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Текст на странице контакты', verbose_name='Текст'),
        ),
    ]
