# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0018_pricepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='pricepage',
            name='text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Текст'),
        ),
    ]
