# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20180216_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
