# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_pricecategorylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('price_name', models.CharField(blank=True, max_length=250)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='home.PriceCategoryList')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
