# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_pricelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='page',
        ),
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
