# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20180216_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricecategorylist',
            name='page',
        ),
        migrations.DeleteModel(
            name='PriceCategoryList',
        ),
    ]
