# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20180216_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Категории цен',
            },
        ),
        migrations.CreateModel(
            name='ListPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ManyToManyField(related_name='category_price', to='home.CategoryPrice', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
