# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 14:23
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_pricepage_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='category_in', to='home.CategoryPrice'),
        ),
    ]
