# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20180217_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listprice',
            name='category',
        ),
        migrations.AddField(
            model_name='categoryprice',
            name='items',
            field=models.ManyToManyField(related_name='price_list', to='home.ListPrice', verbose_name='Категория'),
        ),
    ]
