# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20180217_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryprice',
            name='items',
            field=models.ManyToManyField(related_name='price_list', to='home.ListPrice', verbose_name='Список цен'),
        ),
    ]
