# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0033_testimonialspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ф.И.О.')),
                ('date', models.DateField(verbose_name='Post date')),
                ('text', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image', verbose_name='Изображение')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_images', to='home.TestimonialsPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
