# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_specialistindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('sertificate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ф.И.О.')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='specialistimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='specialistimage',
            name='page',
        ),
        migrations.AddField(
            model_name='specialistpage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ф.И.О.'),
        ),
        migrations.AddField(
            model_name='specialistpage',
            name='text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Текст'),
        ),
        migrations.DeleteModel(
            name='SpecialistImage',
        ),
        migrations.AddField(
            model_name='specialistlist',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sertificates', to='home.SpecialistPage'),
        ),
    ]
