# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20180225_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistlist',
            name='sertificate',
            field=models.CharField(blank=True, max_length=555, null=True, verbose_name='Сертификат'),
        ),
    ]
