# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0037_auto_20180225_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
