# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_specialistpage_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistpage',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стаж работы'),
        ),
    ]
